// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8b4Rq-2zcFwlyUM6gatB-lSRLn1EJ_U',
    appId: '1:871822910314:web:3b1bc312f1adf7aa587b13',
    messagingSenderId: '871822910314',
    projectId: 'chat-material3-2d59b',
    authDomain: 'chat-material3-2d59b.firebaseapp.com',
    storageBucket: 'chat-material3-2d59b.appspot.com',
    measurementId: 'G-PGB9PTMR6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZF232BVwF6-ubfCeZKNknOXLWUEriscc',
    appId: '1:871822910314:android:5ac7250156a69ac6587b13',
    messagingSenderId: '871822910314',
    projectId: 'chat-material3-2d59b',
    storageBucket: 'chat-material3-2d59b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBnOg0w5RikXkBZUlyE7fogEMkte5mkc',
    appId: '1:871822910314:ios:34d947156e84ba8c587b13',
    messagingSenderId: '871822910314',
    projectId: 'chat-material3-2d59b',
    storageBucket: 'chat-material3-2d59b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBnOg0w5RikXkBZUlyE7fogEMkte5mkc',
    appId: '1:871822910314:ios:34d947156e84ba8c587b13',
    messagingSenderId: '871822910314',
    projectId: 'chat-material3-2d59b',
    storageBucket: 'chat-material3-2d59b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd8b4Rq-2zcFwlyUM6gatB-lSRLn1EJ_U',
    appId: '1:871822910314:web:828dced7117a3cbe587b13',
    messagingSenderId: '871822910314',
    projectId: 'chat-material3-2d59b',
    authDomain: 'chat-material3-2d59b.firebaseapp.com',
    storageBucket: 'chat-material3-2d59b.appspot.com',
    measurementId: 'G-G3PF8QY7N5',
  );
}
